name: Run License Tests
on:
  push:
  workflow_dispatch:

jobs:
  license_tests:
    uses: OpenVoiceOS/gh-automations/.github/workflows/license-tests.yml@dev
    with:
      version_file: 'ovos_vad_plugin_webrtcvad/version.py'
